"""Initial migration

Revision ID: 419f7a8b7902
Revises: 39d6d7bb57a4
Create Date: 2025-03-22 13:42:49.980581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419f7a8b7902'
down_revision: Union[str, None] = '39d6d7bb57a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_point_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id_1', sa.Integer(), nullable=False),
    sa.Column('point_id_2', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['point_id_1'], ['map_point.id'], ),
    sa.ForeignKeyConstraint(['point_id_2'], ['map_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_point_connections_id'), 'map_point_connections', ['id'], unique=False)
    op.add_column('map_point', sa.Column('map_point_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'map_point', 'map_point', ['map_point_id'], ['id'])
    op.drop_column('room', 'floor_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('floor_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'map_point', type_='foreignkey')
    op.drop_column('map_point', 'map_point_id')
    op.drop_index(op.f('ix_map_point_connections_id'), table_name='map_point_connections')
    op.drop_table('map_point_connections')
    # ### end Alembic commands ###
