"""Initial migration

Revision ID: 8681d3403524
Revises: 419f7a8b7902
Create Date: 2025-03-22 13:56:52.261055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8681d3403524'
down_revision: Union[str, None] = '419f7a8b7902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('map_point_map_point_id_fkey', 'map_point', type_='foreignkey')
    op.drop_column('map_point', 'map_point_id')
    op.add_column('room', sa.Column('map_point_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room', 'map_point', ['map_point_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'map_point_id')
    op.add_column('map_point', sa.Column('map_point_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('map_point_map_point_id_fkey', 'map_point', 'map_point', ['map_point_id'], ['id'])
    # ### end Alembic commands ###
