"""Initial migration

Revision ID: af778961aa9b
Revises: 
Create Date: 2024-11-25 02:35:10.403437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af778961aa9b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_part",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_building_part_id"), "building_part", ["id"], unique=False)
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("building_part_id", sa.Integer(), nullable=False),
        sa.Column("floor_num", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_part_id"],
            ["building_part.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_room_id"), "room", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_room_id"), table_name="room")
    op.drop_table("room")
    op.drop_index(op.f("ix_building_part_id"), table_name="building_part")
    op.drop_table("building_part")
    # ### end Alembic commands ###
